#@TYPE: Machine
#@NAME: SyMoNeuRaL qemux86-64
#@DESCRIPTION: SyMoNeuRaL custom emulation target for qemux86-64

require conf/machine/include/x86/x86-64.inc
require conf/machine/include/symoneural-qemu-base.inc

# Specify the qemu architecture for runqemu
QB_SYSTEM_NAME = "qemu-system-$(echo qemux86-64 | sed 's/qemu//; s/-64//')"
