require conf/machine/genericx86-64.conf

# Hardware Identity
MACHINE = "symon-x86-workstation"

# Branding and Boot
SYMON_SPLASH_FILE = "workstation_splash.png"

# Hardware Capabilities (Modules handled by GPU include in Distro)
MACHINE_FEATURES += "pci pcie efi screen x86"
