BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "symoneural-bsp"
BBFILE_PATTERN_symoneural-bsp = "^${LAYERDIR}/"
BBFILE_PRIORITY_symoneural-bsp = "6"

LAYERDEPENDS_symoneural-bsp = "core symoneural"
LAYERSERIES_COMPAT_symoneural-bsp = "scarthgap"
