BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "symoneural"
BBFILE_PATTERN_symoneural = "^${LAYERDIR}/"
BBFILE_PRIORITY_symoneural = "7"
LAYERVERSION_symoneural = "1"
LAYERSERIES_COMPAT_symoneural = "scarthgap"
