LCONF_VERSION = "7"
BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /var/yocto/symoneural/openembedded-core/meta \
  /var/yocto/symoneural/meta-poky \
  /var/yocto/symoneural/meta-symoneural \
  /var/yocto/symoneural/meta-symoneural-bsp \
  "
