# Inherit the core SyMoNeuRaL identity and policy
require conf/distro/symonos.conf

DISTRO = "symon-bleeding"
DISTRO_NAME = "SyMoNeuRaL Bleeding Edge (Experimental)"

# Layer on the NVIDIA/GPU specifics
require conf/distro/include/gpu-support-nvidia.inc

# Overwrite the kernel version to the highest available
PREFERRED_VERSION_linux-yocto = "6.6%"

# Add experimental distro features only for this flavor
DISTRO_FEATURES:append = " virtualization kvm"
