DISTRO = "symonos"
DISTRO_NAME = "SymonOS Linux"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "whinlatter"
SDK_VENDOR = "-symoneuralsdk"
SDK_VERSION[vardepvalue] = "${SDK_VERSION}"

MAINTAINER = "Symoneural Maintainer Garrett McDonald"
TARGET_VENDOR = "-symoneural"
LOCALCONF_VERSION = "2"

SYMONEURAL_DEFAULT_DISTRO_FEATURES = "ssh-server-dropbear"
SYMONEURAL_EXTRA_RDEPENDS = "packagegroup-core-boot"
SYMONEURAL_EXTRA_RRECOMMENDS = "kernel-module-af-packet"

DISTRO_EXTRA_RDEPENDS += "${SYMONEURAL_EXTRA_RDEPENDS}"
DISTRO_EXTRA_RRECOMMENDS += "${SYMONEURAL_EXTRA_RRECOMMENDS}"

SYMONEURAL_INIT_MANAGER = "systemd"
INIT_MANAGER ?= "${SYMONEURAL_INIT_MANAGER}"

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"

DISTRO_FEATURES ?= "${DISTRO_FEATURES_DEFAULT} \
                    ${SYMONEURAL_DEFAULT_DISTRO_FEATURES} \
                    argp largefile usbhost wifi xattr nfs \
                    pci x11 opengl wayland vulkan pulseaudio \
                    multiarch pam systemd usrmerge"

PREFERRED_VERSION_linux-yocto ?= "6.6%"
PREFERRED_VERSION_linux-yocto-rt ?= "6.6%"

PACKAGE_CLASSES ?= "package_ipk package-deb package-rpm"

SDK_NAME = "${DISTRO}-${TCLIBC}-${SDKMACHINE}-${IMAGE_BASENAME}-${TUNE_PKGARCH}-${MACHINE}"
SDKPATH = "/opt/${DISTRO}/${DISTRO_VERSION}"
SDKPATHINSTALL = "/opt/${DISTRO}/${SDK_VERSION}"

IMAGE_FSTYPES += "tar.zst ext4 wic"

ERROR_QA = "version-going-backwards"
require conf/distro/include/security_flags.inc
require conf/distro/include/yocto-uninative.inc
require conf/distro/include/no-static-libs.inc
INHERIT += "uninative"

require conf/distro/include/symoneural-world-exclude.inc

INHERIT += "symoneural-sanity"


# Kernel Policy: High-Performance Desktop
PREFERRED_PROVIDER_virtual/kernel = "linux-yocto"
PREFERRED_VERSION_linux-yocto = "6.6%"
