require conf/distro/symonos.conf

DISTRO = "symon-altcfg"
DISTRO_NAME = "SymonOS Alternate (Dev/Test)"

DISTROOVERRIDES = "symonos:symon-altcfg"
#DISTROOVERRIDES = "symonos:linuxstdbase"

SYMONEURAL_INIT_MANAGER:symon-altcfg = "sysvinit"
SYMONEURAL_DISTRO_FEATURES:remove = "systemd"

require conf/distro/include/symoneural-dev-upgrade.inc
