require conf/distro/include/symoneural-floating-revisions.inc
require conf/distro/symonos.conf

DISTRO = "symon-bleeding"
DISTRO_NAME = "SymonOS Bleeding Edge (Unstable)"
DISTROOVERRIDES = "symonos:symon-bleeding"

PREFERRED_PROVIDER_virtual/kernel = "linux-yocto-dev"

SRCREV_machine:pn-linux-yocto-dev ?= "${AUTOREV}"
SRCREV_meta:pn-linux-yocto-dev ?= "${AUTOREV}"
