DISTRO = "symon-tiny"
DISTRO_NAME = "SyMoNeuRaL Tiny Miner OS"

# ACCEPT LICENSES HERE - No more local.conf warnings
LICENSE_FLAGS_ACCEPTED += "commercial xilinx"

TCLIBC = "glibc"
DISTRO_FEATURES = "ipv4 ipv6 usbhost usbgadget virtualization"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "pulseaudio bluez5"
