DISTRO = "symoneural"
DISTRO_NAME = "SyMoNeuRaL OS"
DISTRO_VERSION = "1.0"
DISTRO_CODENAME = "scarthgap"
SDK_VENDOR = "-symosdk"
SDK_VERSION = "${DISTRO_VERSION}"

MAINTAINER = "Garrett Parker Mcdonald"

TARGET_VENDOR = "-symo"

LOCALCONF_VERSION = "2"

DISTRO_FEATURES:append = " virtualization systemd opengl"
DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
