require conf/distro/symonos.conf

DISTRO = "symon-bleeding"
DISTRO_NAME = "SyMoNeuRaL Bleeding Edge (Experimental)"

# Vendor-specific GPU enablement
require conf/distro/include/gpu-support-nvidia.inc

# Overwrite Kernel for Bleeding Edge
# Note: Ensure your layers have 6.12 recipes available
PREFERRED_VERSION_linux-yocto = "6.12%"
PREFERRED_VERSION_linux-yocto-rt = "6.12%"
