POKY_BBLAYERS_CONF_VERSION = "2"
BBPATH = "${TOPDIR}"
BBFILES ?= ""
BBLAYERS ?= " \
  /var/yocto/symoneural/meta \
  /var/yocto/symoneural/meta-symoneural \
  /var/yocto/symoneural/meta-openembedded/meta-oe \
  /var/yocto/symoneural/meta-openembedded/meta-python \
  /var/yocto/symoneural/meta-openembedded/meta-networking \
  /var/yocto/symoneural/meta-clang \
  "
