#!/usr/bin/env bash
set -euo pipefail

# Post-reboot continuation framework (one-shot systemd)
# - Phase 1 (setup.sh): call postreboot_init, postreboot_add_step ..., postreboot_install_service, postreboot_enable_next_boot
# - Phase 2 (next boot): systemd runs the runner, which sources the repo libs and executes queued steps once.

POSTREBOOT_STATE_DIR="/var/lib/kde-deb13-setup"
POSTREBOOT_ENV_FILE="$POSTREBOOT_STATE_DIR/state.env"
POSTREBOOT_QUEUE_FILE="$POSTREBOOT_STATE_DIR/queue.sh"
POSTREBOOT_LOG_FILE="/var/log/kde-deb13-setup-postreboot.log"

POSTREBOOT_SERVICE_NAME="kde-deb13-setup-postreboot.service"
POSTREBOOT_SERVICE_PATH="/etc/systemd/system/${POSTREBOOT_SERVICE_NAME}"
POSTREBOOT_RUNNER_PATH="/usr/local/sbin/kde-deb13-setup-postreboot.sh"

postreboot_init() {
  local repo_dir="$1"

  mkdir -p "$POSTREBOOT_STATE_DIR"

  cat >"$POSTREBOOT_ENV_FILE" <<EOF
# Generated by setup.sh
REPO_DIR="${repo_dir}"
EOF

  # Create (or reset) the queue file with strict-mode header
  cat >"$POSTREBOOT_QUEUE_FILE" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

# Queued post-reboot steps will be appended below as plain function calls.
EOF

  chmod 0600 "$POSTREBOOT_ENV_FILE" || true
  chmod 0700 "$POSTREBOOT_STATE_DIR" || true
  chmod +x "$POSTREBOOT_QUEUE_FILE"
}

postreboot_add_step() {
  local fn="$1"

  # Append as a function call. The runner will source repo libs first, so functions must exist there.
  echo "${fn}" >>"$POSTREBOOT_QUEUE_FILE"
}

postreboot_install_service() {
  mkdir -p "$(dirname "$POSTREBOOT_RUNNER_PATH")"

  # Runner script: sources repo libs + executes queue once, then disables itself.
  cat >"$POSTREBOOT_RUNNER_PATH" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail

POSTREBOOT_STATE_DIR="/var/lib/kde-deb13-setup"
POSTREBOOT_ENV_FILE="$POSTREBOOT_STATE_DIR/state.env"
POSTREBOOT_QUEUE_FILE="$POSTREBOOT_STATE_DIR/queue.sh"
POSTREBOOT_LOG_FILE="/var/log/kde-deb13-setup-postreboot.log"

SERVICE_NAME="kde-deb13-setup-postreboot.service"

exec > >(tee -a "$POSTREBOOT_LOG_FILE") 2>&1

echo "[INFO] Post-reboot continuation started: $(date -Is)"

if [[ ! -f "$POSTREBOOT_ENV_FILE" ]]; then
  echo "[FAIL] Missing env file: $POSTREBOOT_ENV_FILE"
  exit 1
fi

# shellcheck source=/dev/null
. "$POSTREBOOT_ENV_FILE"

if [[ -z "${REPO_DIR:-}" || ! -d "$REPO_DIR" ]]; then
  echo "[FAIL] REPO_DIR is missing or invalid: '${REPO_DIR:-}'"
  exit 1
fi

# Source repo libraries if present (keeps runner resilient if repo evolves)
for f in   "$REPO_DIR/lib/00_core.sh"   "$REPO_DIR/lib/10_pkg.sh"   "$REPO_DIR/lib/20_sources.sh"   "$REPO_DIR/lib/30_base.sh"   "$REPO_DIR/lib/40_gui.sh"   "$REPO_DIR/lib/50_fonts.sh"   "$REPO_DIR/lib/60_devtools.sh"   "$REPO_DIR/lib/70_remote.sh"   "$REPO_DIR/lib/80_nvidia.sh"   "$REPO_DIR/lib/90_postreboot.sh"
do
  if [[ -f "$f" ]]; then
    # shellcheck source=/dev/null
    . "$f"
  fi
done

if [[ ! -f "$POSTREBOOT_QUEUE_FILE" ]]; then
  echo "[WARN] No queue file found ($POSTREBOOT_QUEUE_FILE); nothing to do."
else
  echo "[INFO] Executing queued steps from $POSTREBOOT_QUEUE_FILE"
  # shellcheck source=/dev/null
  . "$POSTREBOOT_QUEUE_FILE"
fi

echo "[OK] Post-reboot continuation complete."

# Disable service so it runs only once
if command -v systemctl >/dev/null 2>&1; then
  systemctl disable --now "$SERVICE_NAME" >/dev/null 2>&1 || true
  systemctl daemon-reload >/dev/null 2>&1 || true
fi

# Mark completion and keep artifacts for debugging
touch "$POSTREBOOT_STATE_DIR/done" || true

echo "[INFO] Post-reboot continuation finished: $(date -Is)"
EOF

  chmod +x "$POSTREBOOT_RUNNER_PATH"

  cat >"$POSTREBOOT_SERVICE_PATH" <<EOF
[Unit]
Description=KDE Debian 13 Setup - Post-reboot continuation (one-shot)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=$POSTREBOOT_RUNNER_PATH
RemainAfterExit=no

[Install]
WantedBy=multi-user.target
EOF

  chmod 0644 "$POSTREBOOT_SERVICE_PATH"

  if command -v systemctl >/dev/null 2>&1; then
    systemctl daemon-reload
  fi
}

postreboot_enable_next_boot() {
  if ! command -v systemctl >/dev/null 2>&1; then
    echo "[FAIL] systemctl not available; cannot schedule post-reboot continuation."
    return 1
  fi

  systemctl enable "$POSTREBOOT_SERVICE_NAME"
  echo "[OK] Scheduled post-reboot continuation for next boot: $POSTREBOOT_SERVICE_NAME"
}

postreboot_disable() {
  if command -v systemctl >/dev/null 2>&1; then
    systemctl disable --now "$POSTREBOOT_SERVICE_NAME" >/dev/null 2>&1 || true
    systemctl daemon-reload >/dev/null 2>&1 || true
  fi
}
