LCONF_VERSION = "7"
BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /var/yocto/symoneural/meta-symoneural/meta \
  /var/yocto/symoneural/meta-symoneural \
  /var/yocto/symoneural/meta-openembedded/meta-oe \
  "
