BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "symon"
BBFILE_PATTERN_symon = "^${LAYERDIR}/"
BBFILE_PRIORITY_symon = "7"
LAYERSERIES_COMPAT_symon = "scarthgap"
