#@TYPE: Machine
#@NAME: SyMoNeuRaL qemuppc
#@DESCRIPTION: SyMoNeuRaL custom emulation target for qemuppc

require conf/machine/include/powerpc/ppc7400.inc
require conf/machine/include/symoneural-qemu-base.inc

# Specify the qemu architecture for runqemu
QB_SYSTEM_NAME = "qemu-system-$(echo qemuppc | sed 's/qemu//; s/-64//')"
