#@TYPE: Machine
#@NAME: SyMoNeuRaL qemuriscv32
#@DESCRIPTION: SyMoNeuRaL custom emulation target for qemuriscv32

require conf/machine/include/riscv/riscv32.inc
require conf/machine/include/symoneural-qemu-base.inc

# Specify the qemu architecture for runqemu
QB_SYSTEM_NAME = "qemu-system-$(echo qemuriscv32 | sed 's/qemu//; s/-64//')"
