#@TYPE: Machine
#@NAME: SyMoNeuRaL qemuriscv64
#@DESCRIPTION: SyMoNeuRaL custom emulation target for qemuriscv64

require conf/machine/include/riscv/riscv64.inc
require conf/machine/include/symoneural-qemu-base.inc

# Specify the qemu architecture for runqemu
QB_SYSTEM_NAME = "qemu-system-$(echo qemuriscv64 | sed 's/qemu//; s/-64//')"
