#@TYPE: Machine
#@NAME: SyMoNeuRaL qemumips
#@DESCRIPTION: SyMoNeuRaL custom emulation target for qemumips

require conf/machine/include/mips/mips32.inc
require conf/machine/include/symoneural-qemu-base.inc

# Specify the qemu architecture for runqemu
QB_SYSTEM_NAME = "qemu-system-$(echo qemumips | sed 's/qemu//; s/-64//')"
