require conf/machine/include/zynq-generic.inc
require conf/machine/zynq-generic.conf
SOC_VARIANT = "7z010"
HOSTNAME = "symoneural-miner"
MACHINE_FEATURES += "usbhost eth"
SERIAL_CONSOLES = "115200;ttyPS0"
# HDF_PATH: Points to your Vivado hardware export
HDF_PATH ?= "${LAYERDIR}/recipes-bsp/hw-design/files/miner_top.xsa"
