#@TYPE: Machine
#@NAME: symoneural-miner-zynq
#@DESCRIPTION: Machine support for SyMoNeuRaL Zynq 7010 Miner.

# 1. Inherit the generic Xilinx Zynq logic
require conf/machine/include/zynq-generic.inc

# 2. Inherit SyMoNeuRaL common Zynq settings
require conf/machine/include/symoneural-zynq-common.inc

# 3. Hardware specific overrides
SOC_VARIANT = "7z010"
HOSTNAME = "symoneural-miner"

# HDF/XSA handoff
HDF_PATH = "${DEPLOY_DIR_IMAGE}/external-hw/miner_top.xsa"
