#@TYPE: Machine
#@NAME: symon-x86-workstation
#@DESCRIPTION: Generic SyMoNeuRaL x86_64 Workstation (Architecture Only)

# 1. Inherit the industry-standard generic x86-64 logic
require conf/machine/genericx86-64.conf

# 2. Define hardware capabilities, not specific brands
# This tells Yocto the board supports high-end graphics and EFI
MACHINE_FEATURES += "pci pcie efi screen x86"

# 3. Use a variable for the splash so it can be overridden
SYMON_SPLASH_FILE ?= "workstation_splash.png"
