#@TYPE: Machine
#@NAME: SyMoNeuRaL qemux86
#@DESCRIPTION: SyMoNeuRaL custom emulation target for qemux86

require conf/machine/include/x86/i586.inc
require conf/machine/include/symoneural-qemu-base.inc

# Specify the qemu architecture for runqemu
QB_SYSTEM_NAME = "qemu-system-$(echo qemux86 | sed 's/qemu//; s/-64//')"
