#@TYPE: Machine
#@NAME: SyMoNeuRaL qemuarm
#@DESCRIPTION: SyMoNeuRaL custom emulation target for qemuarm

require conf/machine/include/arm/armv7a.inc
require conf/machine/include/symoneural-qemu-base.inc

# Specify the qemu architecture for runqemu
QB_SYSTEM_NAME = "qemu-system-$(echo qemuarm | sed 's/qemu//; s/-64//')"
