BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "neural"
BBFILE_PATTERN_neural = "^${LAYERDIR}/"
BBFILE_PRIORITY_neural = "6"
LAYERSERIES_COMPAT_neural = "scarthgap"
